#sudo docker-compose build

version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app #changes in projects automatically updated in docker
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
